<?php

namespace App\Controller\Admin;

use App\Utils\View;

class About extends Page
{

    public static function getLogin($request, $errorMessage = null)
    {
        $content = View::render('admin/about',[
        ]);

        return parent::getPage('Login', $content); // TODO: Change the autogenerated stub
    }

}