<?php

namespace App\Controller\Admin;

use App\Utils\View;

class Contact extends Page
{
    public static function getContact($request, $errorMessage = null)
    {
        $content = View::render('admin/contact',[
        ]);

        return parent::getPage('Login', $content); // TODO: Change the autogenerated stub
    }
}